### ISSUE TITLE
[FEATURE] Support for complex numbers

### ISSUE THREAD

**Issue by Nephty** [Nephty/calculator-cucumber-2024#9]
Add support for complex numbers (e.g. 2+5i), expressions based on complex numbers, and arithmetic operations on those complex numbers. Note that a "normal" number should be considered as a special case of a complex numbers. E.g. 5 = 5+0i; 2.7 = 2.7+0i. The use of complex numbers has an effect on how to compute arithmetic operations. E.g. the square root of -1 is undefined for natural or decimal numbers, while it is defined for complex numbers (sqrt(-1)=i since i*i=-1)
When implementing complex numbers, new operations can be added, such as:

- Computing the modulus (recall that |a+bi| = sqrt(a²+b²)).
- Converting between cartesian, polar and exponential forms. For instance: sqrt(2) + sqrt(2)i (cartesian) = 2 (cosine(pi/4) + i sine (pi/4)) (polar) = 2 e^(i*pi/4) (exponential).

Be careful of operations that either no longer work, have to be defined in an alternate way, or no longer satisfy the same mathematical properties.

**Comment by MrRose765** [comment]
The feature was successfully added to the calculator.

# Represent a number
A complex number is represented by a `MyNumber` class. This class has 2 parameters `real` and `imaginary`. These two parameters are `AbstractValues`. They can either be Int, Real from issue #7 or Rationals from issue #10.

# Modulus
The modulus operator is added and can be calculated in the calculator by adding "|" between the expression to compute the modulus on.
![ModulusImage](https://github.com/Nephty/calculator-cucumber-2024/assets/72945823/4e14c31e-2ba1-4772-a8ce-2cbca7b4a2bd)

# Complex forms 
The three forms can be selected using the `Form` button on the GUI. Each of the forms can and also be used in expressions.
![ComplexForms](https://github.com/Nephty/calculator-cucumber-2024/assets/72945823/d9e07f89-f7c8-45db-b09b-5bd7604665d4)

There may be a problem with precision when going from Polar/Exponential to Cartesian. In the example above, if we switch to Cartesian, it results in `4.0001 - 4.0001i`. This is due to the rounding in the computations of the values.

# Adaptation of the operators

### Square root
The square root operator was adapted to return a complex number when computed on a negative value. We can also compute the square root of a complex number.

### Natural logarithm (Ln)
This operator was also adapted to return a complex number when computed on a negative value. However, it still returns an NaN when computed on zero (Since it's not defined even for complex numbers).  
We can also compute the natural logarithm on complex numbers.

### Sin - Cos
These operators will return an error (outputs NaN and log the error) if they are computed on complex numbers.  
They are not supported by this calculator.

### Others
All other operations available works also with complex numbers with no special cases.
